name: {{project_name}}
description: {{project_description}}
publish_to: {{author}}

version: {{version}}

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.1
  lottie: ^3.0.0
  flutter_easyloading: ^3.0.5
  intl: ^0.18.0
  image_picker: 1.1.2
  permission_handler: ^10.0.0
  dio: ^5.7.0
  flutter_sticky_header: ^0.6.2  # Check for the latest version
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - env/


