name: {{project_name}}
description: "A Flutter project for the raju666 application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.1
  lottie: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - environment/


